2021-03-21 13:09:04,311 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 13:09:51,593 interview.admin 39 INFO     edisonmbli exported 1 candidate records
2021-03-21 13:10:18,391 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 13:10:41,953 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 13:10:45,161 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/recruitment/settings.py changed, reloading.
2021-03-21 13:10:45,551 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 13:10:48,752 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 13:11:00,792 interview.admin 39 INFO     edisonmbli exported 2 candidate records
2021-03-21 13:21:12,707 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/manage.py changed, reloading.
2021-03-21 21:34:13,945 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 21:35:37,674 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 21:50:23,469 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/recruitment/urls.py changed, reloading.
2021-03-21 21:50:25,610 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:06:32,135 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:06:34,134 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:06:56,255 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:06:58,206 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:07:01,752 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:07:03,490 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:07:21,595 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:07:23,053 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:07:26,619 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:07:28,044 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:07:54,380 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:07:55,839 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:07:58,892 django.request 230 ERROR    Internal Server Error: /admin/interview/candidate/4/change/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1569, in _changeform_view
    request, obj, change=not add, fields=flatten_fieldsets(fieldsets)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 679, in get_form
    readonly_fields = self.get_readonly_fields(request, obj)
  File "/Users/edisonlee/Documents/projects/recruitment/interview/admin.py", line 73, in get_readonly_fields
    group_names = self.get_group_name(request.user)
AttributeError: 'CandidateAdmin' object has no attribute 'get_group_name'
2021-03-21 22:08:23,535 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:08:25,261 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:08:28,521 django.request 230 ERROR    Internal Server Error: /admin/interview/candidate/4/change/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1569, in _changeform_view
    request, obj, change=not add, fields=flatten_fieldsets(fieldsets)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 679, in get_form
    readonly_fields = self.get_readonly_fields(request, obj)
  File "/Users/edisonlee/Documents/projects/recruitment/interview/admin.py", line 73, in get_readonly_fields
    group_names = self.get_group_names(request.user)
AttributeError: 'CandidateAdmin' object has no attribute 'get_group_names'
2021-03-21 22:08:37,504 django.request 230 ERROR    Internal Server Error: /admin/interview/candidate/4/change/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1569, in _changeform_view
    request, obj, change=not add, fields=flatten_fieldsets(fieldsets)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 679, in get_form
    readonly_fields = self.get_readonly_fields(request, obj)
  File "/Users/edisonlee/Documents/projects/recruitment/interview/admin.py", line 73, in get_readonly_fields
    group_names = self.get_group_names(request.user)
AttributeError: 'CandidateAdmin' object has no attribute 'get_group_names'
2021-03-21 22:11:50,953 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:11:52,843 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:14:18,883 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:14:21,119 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:15:12,676 interview.admin 83 INFO     interviewer is in user's group for david
2021-03-21 22:15:12,691 interview.admin 83 INFO     interviewer is in user's group for david
2021-03-21 22:19:23,993 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:19:26,297 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:26:56,433 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:26:58,452 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:27:09,184 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:27:10,621 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:27:35,903 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:27:38,249 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:27:54,210 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:27:55,650 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:33:47,301 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:33:49,431 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:34:37,512 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:34:39,547 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:35:08,520 django.request 230 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/edisonlee/Documents/projects/recruitment/interview/admin.py", line 89, in get_changelist_instance
    self.list_editable = self.get_list_editable(request)
  File "/Users/edisonlee/Documents/projects/recruitment/interview/admin.py", line 83, in get_list_editable
    if request.user.is_super_user or 'hr' in group_names:
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/functional.py", line 241, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'is_super_user'
2021-03-21 22:35:22,459 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:35:24,504 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:35:25,702 django.request 230 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/edisonlee/Documents/projects/recruitment/interview/admin.py", line 89, in get_changelist_instance
    self.list_editable = self.get_list_editable(request)
  File "/Users/edisonlee/Documents/projects/recruitment/interview/admin.py", line 83, in get_list_editable
    if request.user.is_super_user() or 'hr' in group_names:
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/functional.py", line 241, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'is_super_user'
2021-03-21 22:35:28,756 django.request 230 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/edisonlee/Documents/projects/recruitment/interview/admin.py", line 89, in get_changelist_instance
    self.list_editable = self.get_list_editable(request)
  File "/Users/edisonlee/Documents/projects/recruitment/interview/admin.py", line 83, in get_list_editable
    if request.user.is_super_user() or 'hr' in group_names:
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/functional.py", line 241, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'is_super_user'
2021-03-21 22:36:11,545 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-21 22:36:29,682 django.request 230 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/edisonlee/Documents/projects/recruitment/interview/admin.py", line 89, in get_changelist_instance
    self.list_editable = self.get_list_editable(request)
  File "/Users/edisonlee/Documents/projects/recruitment/interview/admin.py", line 83, in get_list_editable
    if request.user.is_super_user or 'hr' in group_names:
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/utils/functional.py", line 241, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'is_super_user'
2021-03-21 22:36:59,869 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/interview/admin.py changed, reloading.
2021-03-21 22:37:01,821 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-22 10:46:12,391 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-24 10:18:16,912 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 00:19:15,915 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 00:19:35,140 django.request 230 WARNING  Not Found: /
2021-03-27 00:19:35,705 django.request 230 WARNING  Not Found: /favicon.ico
2021-03-27 16:59:39,229 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 17:00:05,309 django.request 230 WARNING  Not Found: /accounts/profile/
2021-03-27 17:00:27,737 django.request 230 WARNING  Not Found: /accounts/profile/
2021-03-27 17:01:03,967 django.request 230 WARNING  Not Found: /accounts/profile/
2021-03-27 17:03:22,426 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/recruitment/urls.py changed, reloading.
2021-03-27 17:03:23,964 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 17:03:28,691 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/settings/base.py changed, reloading.
2021-03-27 17:03:30,191 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 17:03:44,974 django.request 230 WARNING  Not Found: /accounts/profile/
2021-03-27 17:04:02,533 django.request 230 WARNING  Not Found: /accounts
2021-03-27 17:04:10,199 django.request 230 WARNING  Not Found: /accounts/
2021-03-27 17:04:16,953 django.request 230 WARNING  Not Found: /accounts/profile/
2021-03-27 17:05:17,936 django.request 230 WARNING  Not Found: /
2021-03-27 17:10:54,744 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/settings/base.py changed, reloading.
2021-03-27 17:10:56,259 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 17:11:05,803 django.request 230 WARNING  Not Found: /
2021-03-27 17:11:15,782 django.request 230 WARNING  Not Found: /
2021-03-27 17:12:10,042 django.request 230 WARNING  Not Found: /
2021-03-27 17:14:20,733 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/jobs/urls.py changed, reloading.
2021-03-27 17:14:22,465 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 17:15:28,588 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/jobs/urls.py changed, reloading.
2021-03-27 17:15:55,184 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 17:16:17,970 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 18:46:02,839 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 18:49:44,357 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 18:51:33,749 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 19:49:40,699 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 22:25:21,529 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 22:25:54,140 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 22:26:10,868 django.request 230 ERROR    Internal Server Error: /resume/add/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/generic/edit.py", line 168, in get
    return super().get(request, *args, **kwargs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/generic/edit.py", line 32, in get_form
    form_class = self.get_form_class()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/views/generic/edit.py", line 101, in get_form_class
    return model_forms.modelform_factory(model, fields=self.fields)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/forms/models.py", line 555, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/forms/models.py", line 268, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (picture, attachment) specified for Resume
2021-03-27 22:27:07,310 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/jobs/views.py changed, reloading.
2021-03-27 22:27:08,867 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 22:51:23,916 django.utils.autoreload 240 INFO     /Users/edisonlee/Documents/projects/recruitment/jobs/views.py changed, reloading.
2021-03-27 22:51:25,774 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 22:55:41,849 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 23:12:44,776 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 23:12:57,238 django.request 230 ERROR    Internal Server Error: /resume/add/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' form' from 'bootstrap_form form'
2021-03-27 23:13:52,361 django.request 230 ERROR    Internal Server Error: /resume/add/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'bootstrap_form'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 534, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'bootstrap_form'. Did you forget to register or load this tag?
2021-03-27 23:13:55,899 django.request 230 ERROR    Internal Server Error: /resume/add/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'bootstrap_form'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 534, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'bootstrap_form'. Did you forget to register or load this tag?
2021-03-27 23:14:10,794 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-03-27 23:14:16,592 django.request 230 ERROR    Internal Server Error: /resume/add/
Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'bootstrap_form'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/edisonlee/.virtualenvs/django_dev/lib/python3.7/site-packages/django/template/base.py", line 534, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 4: 'bootstrap_form'. Did you forget to register or load this tag?
